[[pages]]
path = "example_one.py"
name = "st-pages"
icon = "ðŸ“„"

[[pages]]
path = "example_two.py"
name = "Example Two"
icon = ":material/history:"

[[pages]]
path = "example_four.py"
name = "Try hiding pages"
icon = "ðŸ“–"

[[pages]]
path = "example_three.py"

[[pages]]
path = "example_five.py"
name = "Example Five"
icon = "ðŸ§°"
